# Generated by Django 5.1.5 on 2025-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='isBanned',
            field=models.BooleanField(default=False),
        ),
    ]
