# Generated by Django 5.1.5 on 2025-02-10 01:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parent_isbanned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('itemDescription', models.CharField(max_length=250)),
                ('Type', models.CharField(max_length=250)),
                ('imgurl', models.CharField(max_length=250)),
                ('venue', models.CharField(max_length=250)),
            ],
        ),
    ]
